spring:
  profiles:
    active: production
  application:
    name: uaa
  datasource:
    url: jdbc:mysql://dev.czh45671ysak.eu-central-1.rds.amazonaws.com:3306/oauth?useSSL=false
    username: root
    password: Mft_10211488
    driverClassName: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-total: 25
      max-idle: 10
      min-idle: 5
      validation-query: SELECT 1 from dual
      validation-query-timeout: 1
      pool-prepared-statements: true

  http:
    encoding:
      charset: UTF-8

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    serialization:
      write-dates-as-timestamps: false

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false

server:
  port: 9999
  servlet:
    context-path: /uaa
    session:
      timeout: 30m

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://ec2-3-120-208-177.eu-central-1.compute.amazonaws.com:8761/eureka/
    register-with-eureka: false
    fetch-registry: false