spring:
  profiles:
    active: local
  datasource:
    #url:  jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://dev.czh45671ysak.eu-central-1.rds.amazonaws.com:3306/oauth?useSSL=false
    username: root
    password: Mft_10211488

server:
  port: 9999

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.howtodoinjava: INFO
    org.hibernate: INFO